name: fradio_nullsafety
description: A radio component suitable for almost any radio scenario. You will like it.
version: 2.0.0
homepage: https://github.com/Fliggy-Mobile/fradio

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
